/**
 * This file was generated by farrow-api
 * Don't modify it manually
 */

import { createApiPipelineWithUrl } from 'farrow-api-client'

/**
 * {@label CreateCategoryInput}
 */
export type CreateCategoryInput = {
  /**
   * @remarks The name of category
   */
  name: string
  /**
   * @remarks category description
   */
  description: string
  /**
   * @remarks category photo
   */
  image: string
}

/**
 * {@label CreateCategoryOutput}
 */
export type CreateCategoryOutput = {
  /**
   * @remarks The category
   */
  category: Category
}

/**
 * {@label Category}
 */
export type Category = {
  /**
   * @remarks The id of category
   */
  id: number
  /**
   * @remarks The name of category
   */
  name: string
  /**
   * @remarks category description
   */
  description: string
  /**
   * @remarks category photo
   */
  image: string
}

/**
 * {@label DeleteCategoryInput}
 */
export type DeleteCategoryInput = {
  /**
   * @remarks Category id for removing
   */
  id: number
}

/**
 * {@label DeleteCategoryOutput}
 */
export type DeleteCategoryOutput = {
  /**
   * @remarks Category deleted
   */
  category: Category
}

/**
 * {@label GetCategoryListInput}
 */
export type GetCategoryListInput = {
  /**
   * @remarks how many category to get
   */
  limit: number
}

/**
 * {@label GetCategoryListOutput}
 */
export type GetCategoryListOutput = {
  list: Category[]
  count: number
}

export const url = 'http://localhost:3003/api/category'

export const apiPipeline = createApiPipelineWithUrl(url)

export const api = {
  /**
   * @remarks create a new category
   */
  createCategory: (input: CreateCategoryInput) =>
    apiPipeline.invoke({ path: ['createCategory'], input }) as Promise<CreateCategoryOutput>,
  /**
   * @remarks delete one category
   */
  deleteCategory: (input: DeleteCategoryInput) =>
    apiPipeline.invoke({ path: ['deleteCategory'], input }) as Promise<DeleteCategoryOutput>,
  /**
   * @remarks get category list
   */
  getCategoryList: (input: GetCategoryListInput) =>
    apiPipeline.invoke({ path: ['getCategoryList'], input }) as Promise<GetCategoryListOutput>,
}
