/**
 * This file was generated by farrow-api
 * Don't modify it manually
 */

import { createApiPipelineWithUrl } from 'farrow-api-client'

/**
 * {@label CreateOrderInput}
 */
export type CreateOrderInput = {
  petId: number
}

/**
 * {@label InvalidUser}
 */
export type InvalidUser = {
  type: 'INVALID_USER'
  message: string
}

/**
 * {@label CreateOrderSuccess}
 */
export type CreateOrderSuccess = {
  type: 'CREATE_ORDER_SUCCESS'
  order: Order
}

/**
 * {@label Order}
 */
export type Order = {
  id: number
  petId: number
  userId: number
  shipDate: string
  complete: boolean
}

export const url = 'http://localhost:3003/api/order'

export const apiPipeline = createApiPipelineWithUrl(url)

export const api = {
  /**
   * @remarks create a new order
   */
  createOrder: (input: CreateOrderInput) =>
    apiPipeline.invoke({ path: ['createOrder'], input }) as Promise<InvalidUser | CreateOrderSuccess>,
}
